# -----------------------------------------------------------------------------------------------
# this is the seperate call to make all the constant for the project.
# -----------------------------------------------------------------------------------------------


class AuditActions:
    # USER MANAGEMENT.
    USER_REG_SUCCESS = "USER_REGISTRATION_SUCCESS"
    USER_REG_FAILED = "USER_REGISTRATION_VALIDATION_FAILED"
    USER_REG_ERROR = "USER_REGISTRATION_SYSTEM_ERROR"

    # AUTH.
    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    LOGIN_FAILED = "LOGIN_FAILED"

    # PASSWORD MANAGEMENT.
    PASSWORD_CHANGE_SUCCESS = "PASSWORD_CHANGE_SUCCESS"
    PASSWORD_CHANGE_FAILED = "PASSWORD_CHANGE_VALIDATION_FAILED"
    PASSWORD_CHANGE_ERROR = "PASSWORD_CHANGE_SYSTEM_ERROR"

    # USER LOGOUT.
    USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS"
    USER_LOGOUT_FAILED = "USER_LOGOUT_INVALID_SESSION"
    USER_LOGOUT_ERROR = "USER_LOGOUT_SYSTEM_ERROR"

    # PASSWORD RESET REQUEST.
    PASSWORD_RESET_REQUEST_SUCCESS = "PASSWORD_RESET_REQUEST_SUCCESS"
    PASSWORD_RESET_UNKNOWN_EMAIL = "PASSWORD_RESET_REQUEST_UNKNOWN_EMAIL"
    PASSWORD_RESET_INVALID_REQUEST = "PASSWORD_RESET_REQUEST_INVALID_DATA"
    PASSWORD_RESET_REQUEST_ERROR = "PASSWORD_RESET_REQUEST_SYSTEM_ERROR"

    # PASSWORD RESET CONFIRM.
    PASSWORD_RESET_CONFIRM_SUCCESS = "PASSWORD_RESET_CONFIRM_SUCCESS"
    PASSWORD_RESET_CONFIRM_FAILED = "PASSWORD_RESET_CONFIRM_INVALID_TOKEN"
    PASSWORD_RESET_CONFIRM_ERROR = "PASSWORD_RESET_CONFIRM_SYSTEM_ERROR"
